package id.ac.poliban.mi.customlistview;


import java.util.ArrayList;
import java.util.List;

public class CountryData {
    static List<Country> getAllData(){
        List<Country> data = new ArrayList<>();
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/125px-Flag_of_Turkey.svg.png", "Turkey", "Turkey (Turkish: Türkiye [ˈtyɾcije]), officially the Republic of Turkey (Turkish: Türkiye Cumhuriyeti [ˈtyɾcije dʒumˈhuːɾijeti]), is a transcontinental country located mainly on the Anatolian peninsula in Western Asia, with a small portion on the Balkan peninsula in Southeast Europe. East Thrace, the part of Turkey in Europe, is separated from Anatolia by the Sea of Marmara, the Bosphorous and the Dardanelles (collectively called the Turkish Straits).[7] Turkey is bordered by Greece and Bulgaria to its northwest; Georgia to its northeast; Armenia, the Azerbaijani exclave of Nakhchivan and Iran to the east; and Iraq and Syria to the south. Istanbul is the largest city while Ankara is the capital. Approximately 70 to 80 per cent of the country's citizens identify as Turkish.[8][9] Kurds are the largest minority at anywhere from 15 to 20 percent of the population."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png", "Indonesia", "Indonesia (/ˌɪndəˈniːʒə/ IN-də-NEE-zhə, /-ˈniːziə/NEE-zee-ə; Indonesian: [ɪndoˈnesia]), officially the Republic of Indonesia (Indonesian: Republik Indonesia [reˈpublik ɪndoˈnesia]),[a] is a country in Southeast Asia, between the Indian and Pacific oceans. It is the world's largest island country, with more than seventeen thousand islands,[11] and at 1,904,569 square kilometres (735,358 square miles), the 14th largest by land area and 7th in the combined sea and land area.[12] With over 261 million people, it is the world's 4th most populous country as well as the most populous Muslim-majority country.[13] Java, the world's most populous island,[14] is home to more than half of the country's population."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/125px-Flag_of_Thailand.svg.png", "Thailand", "Thailand,[a] officially the Kingdom of Thailand and formerly known as Siam,[b] is a country at the centre of the Southeast Asian Indochinese peninsula composed of 76 provinces. At 513,120 km2 (198,120 sq mi) and over 68 million people, Thailand is the world's 50th-largest country by total area and the 22nd-most-populous country. The capital and largest city is Bangkok, a special administrative area. Thailand is bordered to the north by Myanmar and Laos, to the east by Laos and Cambodia, to the south by the Gulf of Thailand and Malaysia, and to the west by the Andaman Sea and the southern extremity of Myanmar. Its maritime boundaries include Vietnam in the Gulf of Thailand to the southeast, and Indonesia and India on the Andaman Sea to the southwest. It is a unitary state. Although nominally the country is a constitutional monarchy and parliamentary democracy, the most recent coup, in 2014, established a de facto military dictatorship under a junta."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/125px-Flag_of_Singapore.svg.png", "Singapore", "Singapore (/ˈsɪŋ(ɡ)əpɔːr/), officially the Republic of Singapore, is a sovereign island city-state in Southeast Asia. The country is situated one degree (137 kilometres or 85 miles) north of the equator, at the southern tip of the Malay Peninsula, with Indonesia's Riau Islands to the south and Peninsular Malaysia to the north. Singapore's territory consists of one main island along with 62 other islets. Since independence, extensive land reclamation has increased its total size by 23% (130 square kilometres or 50 square miles)."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Amsterdam.svg/100px-Flag_of_Amsterdam.svg.png", "Amsterdam", "Amsterdam (/ˈæmstərdæm/, UK also /ˌæmstərˈdæm/;[10][11] Dutch: [ɑmstərˈdɑm] (About this soundlisten)) is the capital and most populous city of the Netherlands, with a population of 866,737 within the city proper, 1,380,872 in the urban area,[5] and 2,410,960 in the metropolitan area.[9] Amsterdam is in the province of North Holland.[12][13] Amsterdam is colloquially referred to as the \"Venice of the North\" due to its large number of canals which are a UNESCO World Heritage Site."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png", "Arab Saudi", "Arab Saudi[a] (Dengarkani/ˌsɔːdiː əˈreɪbiə/, Dengarkani/ˌsaʊ-/) (Arab: المملكة العربية السعودية), secara resmi di kenal sebagai Kerajaan Arab Saudi atau Kingdom of Saudi Arabia (KSA),[b] adalah sebuah negara Arab di Asia Barat yang mencakup hampir keseluruhan wilayah Semenanjung Arabia. Dengan luas wilayah kira-kira 2150000 km2 (830000 sq mi), Arab Saudi secara geografis merupakan negara terbesar ke lima di Asia dan kedua terbesar di Dunia Arab setelah Aljazair. Arab Saudi berbatasan langsung dengan Yordania dan Irak ke utara, Kuwait ke timur laut, Qatar, Bahrain, dan Uni Emirat Arab ke timur, Oman ke tenggara, dan Yaman ke selatan. Negara ini terpisah dengan Israel dan Mesir oleh Teluk Aqaba. Negara ini adalah satu-satunya negara yang memiliki dua pesisir penting, yakni Laut Merah dan Teluk Persia, dan sebagian besar wilayah Arab Saudi merupakan gurun pasir."));

        return data;
    }
}
